### ISSUE TITLE
absolute path of `workspace.folderBasename1Up`

### ISSUE THREAD

**Issue by WXZhao7** [rioj7/command-variable#28]
I think the absolute path of `workspace.folderBasename1Up` could help directly debug the module in package dir. Now I have to use a complex config that includes `module: ${workspaceFolderBasename}.${command:extension.commandvariable.file.relativeFileDotsNoExtension}` and `cwd: ${workspaceFolder}${pathSeparator}..`. May some command variables like `workspace.prefolder/workspace.folder1Up` and `file.preRelativeFileDotsNoExtension/relativeFileDotsNoExtension1Up` could be introduced?

> file tree
```shell
package
├── A
│   ├── a1.py
│   ├── a2.py
│   ├── __init__.py
├── B
│   ├── b1.py
│   ├── b2.py
│   ├── __init__.py
└── __init__.py
```
> expected configurations:
```json
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Module",
      "type": "python",
      "request": "launch",
      "console": "integratedTerminal",
      "module": "${command:extension.commandvariable.file.preRelativeFileDotsNoExtension}",
      "cwd": "${command:extension.commandvariable.wokspace.prefolder}"
    }
  ]
```

```shell
cd /absolute_path_to_package; *****; python -m package.A.a1
```

**Comment by rioj7** [comment]
@WXZhao7  Can you give an example of:

* full path of file in editor
* path of workspace
* results you expect for the new commands

Your naming is not making clear what is expected

**Comment by WXZhao7** [comment]
@rioj7 Ah... Let me show~

step1: build a multi-layered package structure in the terminal:
> I test it under `~/temp` and relative import is used in this multi-layered package
```shell
cd ~/temp
mkdir package
cd package
touch __init__.py
mkdir subpackage1 subpackage2
touch subpackage1/function1.py subpackage1/__init__.py subpackage2/function2.py subpackage2/__init__.py
echo "from ..subpackage2.function2 import foo" > ~/temp/package/subpackage1/function1.py
echo "foo = True" > ~/temp/package/subpackage2/function2.py
```
step2: open the package with VSC and write `launch.json`:
```shell
code ~/temp/package
```
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Module",
      "type": "python",
      "request": "launch",
      "console": "integratedTerminal",
      "module": "${command:extension.commandvariable.file.relativeFileDotsNoExtension}",
    }
  ]
}
```
step3: select `~/temp/package/subpackage1/function1.py` and `F5` run it as python module.
> click picture to see the error
![image](https://user-images.githubusercontent.com/56864878/156870140-e5d75a2f-507a-493a-9485-b7704612c061.png)

Here I want to run the module `package.subpackage1.function1` with `cwd=~/temp`. So I make a new `launch.json` to solve:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Module",
      "type": "python",
      "request": "launch",
      "console": "integratedTerminal",
      "module": "${workspaceFolderBasename}.${command:extension.commandvariable.file.relativeFileDotsNoExtension}",
      "cwd": "${workspaceFolder}${pathSeparator}.."
    }
  ]
}
```
> click picture to see the results
![image](https://user-images.githubusercontent.com/56864878/156871061-789f6dee-bf4d-42af-8eb1-6c2b0dbb7ac1.png)

I know I could run it successfully with `relativeFileDotsNoExtension` if I change the workspace to `~/temp` by `code ~/temp`.
Here I suggest  adding 
 `${workspaceFolderBasename}.${command:extension.commandvariable.file.relativeFileDotsNoExtension}` and `${workspaceFolder}${pathSeparator}..` as built-in variables in [command-variable](https://github.com/rioj7/command-variable).

Could you understand my idea?  Thank you for your patience!

**Comment by rioj7** [comment]
@WXZhao7 The construct `${workspaceFolder}${pathSeparator}..` looks ugly and could be useful in some other cases.

I have added the commands:

* `extension.commandvariable.workspace.folder1Up` ... `extension.commandvariable.workspace.folder5Up`
* `extension.commandvariable.workspace.folder1UpPosix` ... `extension.commandvariable.workspace.folder5UpPosix`

The construct `${workspaceFolderBasename}.${command:extension.commandvariable.file.relativeFileDotsNoExtension}` is exactly what you want and I can't think of a name that describes clearly what it does.

`extension.commandvariable.file.workspaceFolder1UpRelativeFileDotsNoExtension` or

`extension.commandvariable.file.fileNoExtensionRelativeWorkspaceFolder1UpDots` read possibly worse.

You can construct your own placeholder names with `${input}` variables:

(I will add the variable `${command}` in version 1.32)

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Module",
      "type": "python",
      "request": "launch",
      "console": "integratedTerminal",
      "module": "${input:workspaceFolder1UpRelativeFileDotsNoExtension}",
      "cwd": "${command:extension.commandvariable.workspace.folder1Up}"
    }
  ],
  "inputs": [
    {
      "id": "workspaceFolder1UpRelativeFileDotsNoExtension",
      "type": "command",
      "command": "extension.commandvariable.transform",
      "args": {
        "text": "${workspaceFolderBasename}.${command:extension.commandvariable.file.relativeFileDotsNoExtension}"
      }
    }
  ]
}
```

**Comment by WXZhao7** [comment]
@rioj7 Thanks! The `input` variable is very cool~

**Comment by rioj7** [comment]
@WXZhao7  I have implemented the variable `${command}`. See the README file. Now you can give it any name you like ;-)

**Comment by WXZhao7** [comment]
@rioj7 I still can't send `${command:extension.commandvariable.workspace.folder1Up}` to 'cwd'. I guess the `name` in the `configurations` was considered to be the workspace name because of `You can get info for a particular workspace by supplying a name in the arguments`. 
![image](https://user-images.githubusercontent.com/56864878/156956971-8c8f3322-4398-4f4e-a8b9-e3c2f09ce4d0.png)

**Comment by rioj7** [comment]
@WXZhao7 An undocumented feature/bug (microsoft/vscode#144648) causes the launch config object to be passed as argument to the command.

I have added a workaround/check for a launch config. (v1.32.1)
